# file: mysql/tasks/main.yml

- include: install.yml
- include: configure.yml
- include: secure.yml
- include: databases.yml
- include: users.yml
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
