# file: mysql/tasks/secure.yml

- name: MySQL | Set the root password.
  mysql_user:
    user: root
    host: "{{item}}"
    password: $mysql_root_password
  with_items:
   - "{{ ansible_hostname}}"
   - "%"
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: MySQL | Set the root password.
  mysql_user:
    user: root
    host: "{{item}}"
    password: $mysql_root_password
  with_items:
   - "%"
   - ::1
   - localhost
  when: ansible_hostname == 'localhost'

- name: MySQL | Configure MySql for easy access as root user
  template:
    src: root_dot_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: MySQL | Remove anonymous MySQL server user
  mysql_user:
    name: ""
    host: "{{item}}"
    state: absent
  with_items:
    - "{{ansible_hostname}}"
    - localhost

- name: MySQL | Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
