name: Enlightn

on: [push, pull_request]

jobs:
  enlightn:
    env:
      ENLIGHTN_USERNAME: ${{ secrets.ENLIGHTN_USERNAME }}
      ENLIGHTN_API_TOKEN: ${{ secrets.ENLIGHTN_API_TOKEN }}
      ENLIGHTN_GITHUB_REPO: ${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, json
          coverage: none

      - name: Install Composer dependencies with Enlightn Pro
        if: env.ENLIGHTN_API_TOKEN
        run: |
          composer config http-basic.satis.laravel-enlightn.com "$ENLIGHTN_USERNAME" "$ENLIGHTN_API_TOKEN"
          composer config repositories.enlightn composer https://satis.laravel-enlightn.com
          composer require --prefer-dist --no-interaction enlightn/enlightnpro

      - name: Install Composer dependencies
        if: ${{ !env.ENLIGHTN_API_TOKEN }}
        run: composer install --prefer-dist --no-interaction

      - name: Run Enlightn Checks and Report
        if: env.ENLIGHTN_API_TOKEN
        run: |
          cp .env.example .env
          php artisan enlightn --ci --report

      - name: Run Enlightn Checks
        if: ! env.ENLIGHTN_API_TOKEN
        run: |
          cp .env.example .env
          php artisan enlightn --ci
